/// TESTING ///
export const REDUXTEST = 'REDUXTEST';
export const SHOWSTATE = 'SHOWSTATE';
export const MAINREDUCERTEST = 'MAINREDUCERTEST';
/// MAIN /// 
export const ASSIGNBURGERID = 'ASSIGNBURGERID';
export const PUSHBURGER = 'PUSHBURGER';
export const TOGGLEMENU = 'TOGGLEMENU';
export const RESET = 'RESET';
export const SHOWMENU = 'SHOWMENU';
export const GRANDTOTAL = 'GRANDTOTAL';
export const LETSEAT = 'LETSEAT';
export const REMOVEBURGER = 'REMOVEBURGER';
/// BUILDER /// 

export const INGTOTAL = 'INGTOTAL';
export const BURGERTOTAL = 'BURGERTOTAL';
// export const SUMINGREDIENTS = 'SUMINGREDIENTS';
export const CHECKINGLENGTH = 'CHECKINGLENGTH';
export const ADDINGHANDLER = 'ADDINGHANDLER';
export const REMOVEINGHANDLER = 'REMOVEINGHANDLER';
export const DISABLELESSBUTTONS = 'DISABLELESSBUTTONS';
export const SWITCHINGREDIENTNAME = 'SWITCHINGREDIENTNAME';
export const ORDERBURGER = 'ORDERBURGER';
export const ENABLELESSBUTTONS = 'ENABLELESSBUTTONS'